export const users = [
    'Liam Carter', 'Olivia Bennett','Noah Turner','Emma Collins',
    'William Harris','Ava Mitchell','James Brooks','Sophia Reed',
    'Benjamin Ward','Isabella Gray','Lucas Hayes','Mia Foster',
    'Henry Morgan','Charlotte Perry','Alexander Jenkins','Amelia Bryant',
    'Ethan Sullivan','Harper Cooper','Michael Adams','Evelyn Torres',
    'Daniel Hughes','Abigail Price','Matthew Rivera','Ella Stewart',
    'Samuel Long','Scarlett Rogers','Joseph Butler','Victoria Barnes',
    'David Simmons','Luna Coleman','Andrew Powell','Grace Howard',
    'Joshua Sanders','Chloe Ross','Christopher Peterson','Penelope Morris',
    'Gabriel Jenkins','Layla Reed','Anthony Murphy','Riley Kelly',
    'Isaac Evans','Zoey Cox','Nathan Ward','Hannah Foster','Thomas Brooks',
    'Aria Cook','Leo Murphy','Camila Parker','Owen Mitchell',
    'Lily Gonzales','Julian Howard','Nora Russell','Jack Diaz',
    'Ellie Powell','Aaron Foster','Hazel Simmons','Caleb Perry',
    'Aurora James','Charles Watson','Savannah Price','Christopher Cooper',
    'Addison Barnes','Miles Rivera','Stella Murphy','Eli Parker',
    'Paisley Adams','Jonathan Reed','Skylar Peterson','Connor Gray',
    'Violet Jenkins','Jeremiah Hughes','Brooklyn Ward','Adrian Foster',
    'Claire Sanders','Hunter James','Lucy Rogers','Christian Butler',
    'Anna Stewart','Colton Hayes','Everly Howard','Austin Cox',
    'Naomi Kelly','Parker Long','Elena Gonzales','Adam Torres',
    'Kennedy Hughes','Zachary Coleman','Leah Ross','Evan Powell',
    'Madeline Foster','Brayden Barnes','Aubrey Bryant','Jordan Simmons',
    'Bella Russell','Robert Adams','Kinsley Murphy','Dominic Price',
    'Maya Mitchell','Ian Rivera','Samantha Perry',
    'Gabriella Flores', 'Caleb Richardson',
    'Victoria Simmons', 'Dominic Howard', 'Madison Lee',
    'Zachary Bennett', 'Julia Mitchell', 'Elias Morgan', 
];

export const categories = [
    ['Food Support', 'Requests for meal preparation, food delivery, grocery shopping, or assistance accessing food banks and nutritional support.'],
    ['Transportation', 'Requests for rides to medical appointments, grocery shopping, errands, or transportation for elderly or disabled community members.'],
    ['Elderly Care', 'Requests for befriending visits, social companionship, assistance with daily activities, or emotional support for isolated seniors.'],
    ['Healthcare Support', 'Requests for accompaniment to medical appointments, medication reminders, basic health monitoring, or connecting with healthcare services.'],
    ['Childcare Support', 'Requests for babysitting, tutoring, mentoring children, after-school care, or support for single parents and families in need.'],
    ['Home Maintenance', 'Requests for basic home repairs, cleaning assistance, gardening, organizing, or help with household tasks for those unable to manage independently.'],
    ['Digital Assistance', 'Requests for assistance with online services, device setup, digital literacy training, or help navigating government websites and applications.'],
    ['Educational Support', 'Requests for tutoring, language practice, job interview preparation, resume writing, or skills training for personal development.'],
    ['Emergency Assistance', 'Urgent requests for temporary shelter, crisis counseling, financial guidance, or immediate support during personal emergencies.'],
    ['Social Support', 'Requests for help joining community activities, finding local resources, building social networks, or overcoming isolation and loneliness.']
];

export const serviceRequests = [
  ['Need grocery shopping help', 'Elderly person unable to drive seeking assistance with weekly grocery shopping and errands', 'Food Support'],
  ['Ride to medical appointment', 'Single mother needs transportation to doctor appointment next Tuesday at 2pm', 'Transportation'],
  ['Weekly companion visits', 'Isolated senior looking for friendly visitor to chat and play cards once a week', 'Elderly Care'],
  ['Help with medication reminders', 'Elderly gentleman needs someone to help organize pills and provide daily check-ins', 'Healthcare Support'],
  ['After-school childcare needed', 'Working single parent needs help picking up kids from school and watching them until 6pm', 'Childcare Support'],
  ['Leaky faucet repair', 'Senior citizen needs help fixing a dripping kitchen faucet and replacing washers', 'Home Maintenance'],
  ['Computer setup assistance', 'Elderly woman needs help setting up new tablet and learning to video call family', 'Digital Assistance'],
  ['English conversation practice', 'New immigrant seeking volunteer to practice English conversation skills weekly', 'Educational Support'],
  ['Temporary meal assistance', 'Family facing job loss needs help with prepared meals for the next two weeks', 'Emergency Assistance'],
  ['Help joining community activities', 'Shy teenager needs support finding and joining local youth groups or clubs', 'Social Support'],
  ['Dog walking during recovery', 'Person recovering from surgery needs daily dog walking help for 3 weeks', 'Home Maintenance'],
  ['Tutoring for struggling student', 'Middle school student needs math tutoring twice a week to improve grades', 'Educational Support'],
  ['Lawn mowing assistance', 'Disabled veteran needs help maintaining yard and basic outdoor cleanup', 'Home Maintenance'],
  ['Hospital visit companion', 'Elderly patient needs someone to accompany them to chemotherapy sessions', 'Healthcare Support'],
  ['Moving day help', 'Single mother needs volunteers to help pack and move to new apartment this weekend', 'Emergency Assistance'],
  ['Food bank pickup', 'Senior with mobility issues needs help collecting monthly food assistance', 'Food Support'],
  ['Airport transportation', 'Elderly couple needs ride to airport for important family visit', 'Transportation'],
  ['Light housekeeping help', 'Recovering stroke patient needs assistance with basic cleaning tasks', 'Elderly Care'],
  ['Prescription pickup', 'Homebound senior needs regular help collecting medications from pharmacy', 'Healthcare Support'],
  ['Babysitting for job interview', 'Single parent needs childcare coverage during important job interview', 'Childcare Support'],
  ['Garden maintenance', 'Elderly homeowner needs help with weeding and basic garden upkeep', 'Home Maintenance'],
  ['Smartphone tutorial', 'Senior citizen wants to learn basic smartphone functions to stay connected', 'Digital Assistance'],
  ['Reading comprehension help', 'Elementary student needs support improving reading skills and confidence', 'Educational Support'],
  ['Emergency childcare', 'Parent hospitalized unexpectedly needs immediate help watching two young children', 'Emergency Assistance'],
  ['Senior center transportation', 'Isolated elderly person needs rides to weekly senior center activities', 'Social Support'],
  ['Meal preparation assistance', 'New mother needs help preparing healthy meals during postpartum recovery', 'Food Support'],
  ['Physical therapy transport', 'Disabled individual needs reliable transportation to twice-weekly PT sessions', 'Transportation'],
  ['Technology support for senior', 'Elderly person needs help learning to use email and online banking safely', 'Digital Assistance'],
  ['Homework supervision', 'Working parent needs someone to supervise children doing homework after school', 'Childcare Support'],
  ['Minor home repairs', 'Single elderly woman needs help with loose door handles and squeaky hinges', 'Home Maintenance'],
  ['Grief counseling companion', 'Widowed senior needs emotional support and companionship during difficult time', 'Elderly Care'],
  ['Medical appointment scheduling', 'Overwhelmed caregiver needs help coordinating multiple doctor appointments', 'Healthcare Support'],
  ['Job application assistance', 'Unemployed individual needs help filling out online job applications', 'Educational Support'],
  ['Utility bill crisis help', 'Family facing shut-off notices needs immediate assistance with utility payments', 'Emergency Assistance'],
  ['Social event accompaniment', 'Socially anxious person needs support attending community events', 'Social Support'],
  ['Special diet meal prep', 'Diabetic senior needs help preparing appropriate meals following dietary restrictions', 'Food Support'],
  ['Wheelchair accessible transport', 'Disabled person needs rides to medical appointments with wheelchair accommodation', 'Transportation'],
  ['Daily check-in calls', 'Isolated elderly person needs someone to call daily for safety and companionship', 'Elderly Care'],
  ['Insurance paperwork help', 'Confused senior needs assistance navigating health insurance claims and forms', 'Healthcare Support'],
  ['Summer camp transportation', 'Single parent needs help getting children to and from summer day camp', 'Childcare Support'],
  ['Seasonal home preparation', 'Elderly homeowner needs help winterizing house and cleaning gutters', 'Home Maintenance'],
  ['Online shopping tutorial', 'Senior wants to learn safe online shopping for groceries and necessities', 'Digital Assistance'],
  ['GED study support', 'Adult learner needs tutoring help preparing for high school equivalency exam', 'Educational Support'],
  ['Disaster cleanup help', 'Family affected by flooding needs volunteers to help with cleanup efforts', 'Emergency Assistance'],
  ['Church service transportation', 'Homebound elderly person misses attending weekly religious services', 'Social Support'],
  ['Nutrition education', 'Low-income family needs help learning to prepare healthy meals on budget', 'Food Support'],
  ['Work commute assistance', 'Person without car needs temporary rides to new job until transportation arranged', 'Transportation'],
  ['Respite care for caregiver', 'Exhausted caregiver needs someone to sit with elderly parent for few hours weekly', 'Elderly Care'],
  ['Physical therapy exercises', 'Recovering patient needs encouragement and supervision doing prescribed exercises', 'Healthcare Support'],
  ['Playdate supervision', 'Working single parent needs help organizing and supervising children playdates', 'Childcare Support'],
  ['Winter coat distribution', 'Low-income families need warm coats for winter season', 'Food Support'],
  ['Home safety inspection', 'Elderly resident requests assessment of fall hazards at home', 'Home Maintenance'],
  ['Mental health counseling', 'Person seeking volunteer for weekly mental health support sessions', 'Healthcare Support'],
  ['Transportation to job training', 'Unemployed individual needs rides to job training classes twice weekly', 'Transportation'],
  ['Grocery delivery for disabled', 'Disabled individual requires regular grocery delivery', 'Food Support'],
  ['Child tutoring in reading', 'Elementary student needs help improving literacy skills', 'Educational Support'],
  ['Pet care during vacation', 'Senior needs volunteer to care for dog and cat during trip', 'Home Maintenance'],
  ['Help setting up email', 'New user requires assistance creating and using an email account', 'Digital Assistance'],
  ['Light gardening help', 'Senior homeowner needs basic garden upkeep weekly', 'Home Maintenance'],
  ['Assistance with prescription management', 'Elderly person needs help organizing and understanding medications', 'Healthcare Support'],
  ['Meal prep for diabetic diet', 'Person newly diagnosed with diabetes needs help preparing meals', 'Food Support'],
  ['Errand running', 'Busy single parent needs help running errands like post office and bank', 'Transportation'],
  ['Technology tutorial for seniors', 'Group session teaching basics of smartphone and internet', 'Digital Assistance'],
  ['Support joining support groups', 'Isolated individual wants help finding local support groups', 'Social Support'],
  ['Household organization', 'Senior needs help decluttering and organizing home', 'Home Maintenance'],
  ['Support for new immigrant parent', 'Parent seeking help for childcare and schooling questions', 'Childcare Support'],
  ['Volunteer driver for vaccinations', 'Assistance needed providing rides for vaccination appointments', 'Healthcare Support'],
  ['Pet grooming assistance', 'Senior needs volunteer to help with pet grooming', 'Home Maintenance'],
  ['Organizing community events', 'Volunteer help needed for planning neighborhood social events', 'Social Support'],
  ['Home heating assistance', 'Elderly person needs help with winter heating system maintenance', 'Home Maintenance'],
  ['Computer virus removal', 'Assistance needed for cleaning virus-infected PC', 'Digital Assistance'],
  ['Help completing government forms', 'Senior requires assistance filling out government benefit applications', 'Social Support'],
  ['Emergency childcare backup', 'Working parent needs occasional backup childcare during emergencies', 'Childcare Support'],
  ['Physical therapy transportation', 'Senior requires transportation support to therapy sessions', 'Healthcare Support'],
  ['Weekly phone call check-ins', 'Isolated senior needs regular safety phone calls', 'Elderly Care'],
  ['Assistance with tax filing', 'Low-income individual needs help preparing tax returns', 'Educational Support'],
  ['Community garden support', 'Volunteer needed to maintain public community garden', 'Social Support'],
  ['Help creating a resume', 'Unemployed individual needs assistance building a resume', 'Educational Support'],
  ['Meal delivery for homebound', 'Homebound senior requires meal deliveries daily', 'Food Support'],
  ['Home cleaning help', 'Disabled person needs weekly cleaning assistance', 'Home Maintenance'],
  ['Assistance with using public transit', 'Volunteer needed for training on local public transport options', 'Transportation'],
  ['Medical equipment delivery', 'Person needs help receiving and setting up medical equipment', 'Healthcare Support'],
  ['Homework help for teens', 'Teenager needs tutoring assistance in math and science', 'Educational Support'],
  ['Advice on healthy eating', 'Family wants guidance on affordable nutritious meals', 'Food Support'],
  ['Help with social media setup', 'Senior wants help learning to use social media safely', 'Digital Assistance'],
  ['Caregiver respite support', 'Primary caregiver needs temporary relief help for elderly relative', 'Elderly Care'],
  ['Seasonal decorating help', 'Senior requests assistance with holiday decorations', 'Home Maintenance'],
  ['Phone setup and tutorials', 'Person new to smartphone needs help setting it up', 'Digital Assistance'],
  ['Transportation for community classes', 'Low-income person needs rides to community education classes', 'Transportation'],
  ['Help with legal forms', 'Individual needs support understanding and completing legal paperwork', 'Social Support'],
  ['Pet walking assistance', 'Person recovering from injury needs help walking their dog daily', 'Home Maintenance'],
  ['Language learning support', 'Immigrant seeking weekly conversation partner to practice English', 'Educational Support'],
  ['Temporary financial counseling', 'Family facing unexpected bills needs help budgeting and managing expenses', 'Emergency Assistance'],
  ['Senior technology classes', 'Group of seniors want weekly digital literacy classes for smartphones and tablets', 'Digital Assistance'],
  ['Grocery assistance for disabled', 'Homebound disabled person needs help with shopping and meal prep', 'Food Support'],
  ['Transportation to therapy', 'Patient requires rides to physical therapy twice weekly', 'Transportation'],
  ['Child mentoring program', 'Youth looking for mentor to provide guidance and support after school', 'Childcare Support'],
  ['Emergency shelter placement', 'Homeless individual needs immediate access to safe shelter', 'Emergency Assistance'],
  ['Home cleaning for elderly', 'Elderly person needs help with thorough home cleaning and sanitation', 'Home Maintenance'],
  ['Mental health peer support', 'Adult seeking connection with peer support group for anxiety and depression', 'Healthcare Support']
];
